In [28]:
import numpy as np

def read_pdb(file_path):
    coordinates = []
    with open(file_path, 'r') as pdb_file:
        for line in pdb_file:
            if line.startswith('ATOM'):
                x = float(line[30:38])
                y = float(line[38:46])
                z = float(line[46:54])
                coordinates.append([x, y, z])
    return np.array(coordinates)

def write_pdb(file_path,coordinates,filla):
    with open(file_path, 'r') as pdb_file:
        for line in pdb_file:
            if line.startswith('ATOM'):
                line[30:38]=valor
                y = float(line[38:46])
                z = float(line[46:54])
                coordinates.append([x, y, z])
                
    return np.array(coordinates)


file_path = 'tre-copy.pdb'  # Ruta al archivo PDB
coordinates = read_pdb(file_path)

print("Matriz de coordenadas cartesianas:")
print(coordinates)



Matriz de coordenadas cartesianas:
[[ 0.613  1.415 -0.392]
 [ 1.163  1.202 -1.711]
 [ 1.057  2.63   0.24 ]
 [-0.927  1.412 -0.444]
 [ 2.59   1.071 -1.719]
 [ 0.559  3.873 -0.298]
 [-1.377  2.591 -1.311]
 [-1.463  0.184 -0.947]
 [ 3.099 -0.009 -0.951]
 [ 3.161  1.088 -3.164]
 [-0.939  3.895 -0.651]
 [ 0.848  4.97   0.745]
 [-2.798  2.61  -1.502]
 [ 2.956 -1.313 -1.531]
 [ 3.262 -0.277 -3.85 ]
 [ 2.432  1.97  -4.045]
 [-1.174  4.983 -1.561]
 [ 0.263  4.618  2.008]
 [ 3.609 -1.438 -2.915]
 [ 3.638 -2.304 -0.556]
 [ 4.289 -0.211 -4.868]
 [ 3.193 -2.684 -3.503]
 [ 4.982 -1.886 -0.285]
 [ 0.932  0.588  0.238]
 [-1.326  1.534  0.568]
 [ 2.971  1.984 -1.252]
 [ 1.144  4.108 -1.196]
 [-0.967  2.514 -2.317]
 [-1.617  0.293 -1.903]
 [ 4.175  1.506 -3.108]
 [-1.561  4.075  0.236]
 [ 1.924  5.072  0.916]
 [ 0.448  5.94   0.447]
 [-3.195  2.002 -0.84 ]
 [ 1.893 -1.569 -1.59 ]
 [ 2.344 -0.496 -4.407]
 [ 1.807  2.48  -3.496]
 [-1.969  4.75  -2.077]
 [ 0.69   3.786  2.281]
 [ 4.695 -1.494 -2.819]
 [ 3.

In [29]:
transposed_coordinates = coordinates.transpose()  # Método transpose()
# O también puedes usar: transposed_coordinates = coordinates.T  # Propiedad .T

print("\nMatriz transpuesta de coordenadas cartesianas:")
print(transposed_coordinates)


Matriz transpuesta de coordenadas cartesianas:
[[ 0.613  1.163  1.057 -0.927  2.59   0.559 -1.377 -1.463  3.099  3.161
  -0.939  0.848 -2.798  2.956  3.262  2.432 -1.174  0.263  3.609  3.638
   4.289  3.193  4.982  0.932 -1.326  2.971  1.144 -0.967 -1.617  4.175
  -1.561  1.924  0.448 -3.195  1.893  2.344  1.807 -1.969  0.69   4.695
   3.113  3.671  4.075  2.336  4.927]
 [ 1.415  1.202  2.63   1.412  1.071  3.873  2.591  0.184 -0.009  1.088
   3.895  4.97   2.61  -1.313 -0.277  1.97   4.983  4.618 -1.438 -2.304
  -0.211 -2.684 -1.886  0.588  1.534  1.984  4.108  2.514  0.293  1.506
   4.075  5.072  5.94   2.002 -1.569 -0.496  2.48   4.75   3.786 -1.494
  -2.318 -3.318  0.544 -2.568 -0.943]
 [-0.392 -1.711  0.24  -0.444 -1.719 -0.298 -1.311 -0.947 -0.951 -3.164
  -0.651  0.745 -1.502 -1.531 -3.85  -4.045 -1.561  2.008 -2.915 -0.556
  -4.868 -3.503 -0.285  0.238  0.568 -1.252 -1.196 -2.317 -1.903 -3.108
   0.236  0.916  0.447 -0.84  -1.59  -4.407 -3.496 -2.077  2.281 -2.819
   0.397 -0.

In [30]:
import numpy as np

def euler_rotation_matrix(phi, theta, psi):
    """
    Calcula la matriz de rotación en 3D según los ángulos de Euler (phi, theta, psi).
    
    Args:
        phi (float): Ángulo de Euler phi en radianes.
        theta (float): Ángulo de Euler theta en radianes.
        psi (float): Ángulo de Euler psi en radianes.
        
    Returns:
        numpy.ndarray: Matriz de rotación en 3D.
    """
    R_x = np.array([[1, 0, 0],
                    [0, np.cos(phi), -np.sin(phi)],
                    [0, np.sin(phi), np.cos(phi)]])
    
    R_y = np.array([[np.cos(theta), 0, np.sin(theta)],
                    [0, 1, 0],
                    [-np.sin(theta), 0, np.cos(theta)]])
    
    R_z = np.array([[np.cos(psi), -np.sin(psi), 0],
                    [np.sin(psi), np.cos(psi), 0],
                    [0, 0, 1]])
    
    # Combinar las tres rotaciones
    R = np.dot(R_z, np.dot(R_y, R_x))
    
    return R

# Ejemplo de uso
phi = np.pi/4  # Ángulo de Euler phi (en radianes)
theta = np.pi/3  # Ángulo de Euler theta (en radianes)
psi = np.pi/6  # Ángulo de Euler psi (en radianes)

# Calcular la matriz de rotación
R = euler_rotation_matrix(phi, theta, psi)

print("Matriz de rotación:")
print(R)


Matriz de rotación:
[[ 0.4330127   0.1767767   0.88388348]
 [ 0.25        0.91855865 -0.30618622]
 [-0.8660254   0.35355339  0.35355339]]


ara mulitpliquem la matriu de rotació per la creada anteriorment la transposada

In [31]:
R@transposed_coordinates

array([[ 1.69093487e-01, -7.96245268e-01,  1.13474917e+00,
        -5.44238344e-01, -2.08564958e-01,  6.63312965e-01,
        -1.29700131e+00, -1.43800832e+00,  4.99742187e-01,
        -1.23552112e+00, -2.93461842e-01,  1.90426814e+00,
        -2.07777535e+00, -3.05347857e-01, -2.03943110e+00,
        -2.17397168e+00, -1.00722075e+00,  2.70507514e+00,
        -1.26798238e+00,  6.76567491e-01, -2.48285317e+00,
        -2.18810291e+00,  1.57196164e+00,  7.17876802e-01,
         1.99046423e-01,  5.30583588e-01,  1.64440557e-01,
        -2.02226469e+00, -2.33041622e+00, -6.73056111e-01,
         2.53028706e-01,  2.53936510e+00,  1.63913917e+00,
        -1.77203076e+00, -8.63044318e-01, -2.96797395e+00,
        -1.86919648e+00, -1.84873869e+00,  2.98419354e+00,
        -7.22777268e-01,  1.28910190e+00,  1.53632533e-01,
        -2.95116836e+00, -2.92936520e+00,  1.92963005e+00],
       [ 1.57303549e+00,  1.91874212e+00,  2.60657457e+00,
         1.20120150e+00,  2.15761043e+00,  3.78857116e+

In [32]:
import numpy as np

def read_pdb(file_path):
    coordinates = []
    with open(file_path, 'r') as pdb_file:
        for line in pdb_file:
            if line.startswith('ATOM'):
                x = float(line[30:38])
                y = float(line[38:46])
                z = float(line[46:54])
                coordinates.append([x, y, z])
    return np.array(coordinates)

def write_pdb(file_path, coordinates):
    with open(file_path, 'w') as pdb_file:
        for coord in coordinates:
            x_str = f"{coord[0]:8.3f}"
            y_str = f"{coord[1]:8.3f}"
            z_str = f"{coord[2]:8.3f}"
            line = f"ATOM      1  CA  GLY A   1     {x_str}{y_str}{z_str}\n"
            pdb_file.write(line)

file_path = 'tre-copy.pdb'
coordinates = read_pdb(file_path)

print("Matriz de coordenadas cartesianas:")
print(coordinates)

# Definir ángulos de Euler
phi = np.pi / 4  # Ángulo de Euler phi (en radianes)
theta = np.pi / 3  # Ángulo de Euler theta (en radianes)
psi = np.pi / 6  # Ángulo de Euler psi (en radianes)

# Calcular la matriz de rotación
R = euler_rotation_matrix(phi, theta, psi)

# Aplicar la rotación a las coordenadas
rotated_coordinates = np.dot(R, coordinates.T).T

print("\nCoordenadas rotadas:")
print(rotated_coordinates)

# Escribir las coordenadas rotadas en un nuevo archivo PDB
write_pdb('rotated.pdb', rotated_coordinates)


Matriz de coordenadas cartesianas:
[[ 0.613  1.415 -0.392]
 [ 1.163  1.202 -1.711]
 [ 1.057  2.63   0.24 ]
 [-0.927  1.412 -0.444]
 [ 2.59   1.071 -1.719]
 [ 0.559  3.873 -0.298]
 [-1.377  2.591 -1.311]
 [-1.463  0.184 -0.947]
 [ 3.099 -0.009 -0.951]
 [ 3.161  1.088 -3.164]
 [-0.939  3.895 -0.651]
 [ 0.848  4.97   0.745]
 [-2.798  2.61  -1.502]
 [ 2.956 -1.313 -1.531]
 [ 3.262 -0.277 -3.85 ]
 [ 2.432  1.97  -4.045]
 [-1.174  4.983 -1.561]
 [ 0.263  4.618  2.008]
 [ 3.609 -1.438 -2.915]
 [ 3.638 -2.304 -0.556]
 [ 4.289 -0.211 -4.868]
 [ 3.193 -2.684 -3.503]
 [ 4.982 -1.886 -0.285]
 [ 0.932  0.588  0.238]
 [-1.326  1.534  0.568]
 [ 2.971  1.984 -1.252]
 [ 1.144  4.108 -1.196]
 [-0.967  2.514 -2.317]
 [-1.617  0.293 -1.903]
 [ 4.175  1.506 -3.108]
 [-1.561  4.075  0.236]
 [ 1.924  5.072  0.916]
 [ 0.448  5.94   0.447]
 [-3.195  2.002 -0.84 ]
 [ 1.893 -1.569 -1.59 ]
 [ 2.344 -0.496 -4.407]
 [ 1.807  2.48  -3.496]
 [-1.969  4.75  -2.077]
 [ 0.69   3.786  2.281]
 [ 4.695 -1.494 -2.819]
 [ 3.

In [33]:
import numpy as np

def euler_rotation_matrix(phi, theta, psi):
    """
    Calcula la matriz de rotación en 3D según los ángulos de Euler (phi, theta, psi).
    
    Args:
        phi (float): Ángulo de Euler phi en radianes.
        theta (float): Ángulo de Euler theta en radianes.
        psi (float): Ángulo de Euler psi en radianes.
        
    Returns:
        numpy.ndarray: Matriz de rotación en 3D.
    """
    R_x = np.array([[1, 0, 0],
                    [0, np.cos(phi), -np.sin(phi)],
                    [0, np.sin(phi), np.cos(phi)]])
    
    R_y = np.array([[np.cos(theta), 0, np.sin(theta)],
                    [0, 1, 0],
                    [-np.sin(theta), 0, np.cos(theta)]])
    
    R_z = np.array([[np.cos(psi), -np.sin(psi), 0],
                    [np.sin(psi), np.cos(psi), 0],
                    [0, 0, 1]])
    
    # Combinar las tres rotaciones
    R = np.dot(R_z, np.dot(R_y, R_x))
    
    return R

# Ahora puedes usar esta función en tu código para calcular la matriz de rotación.


In [34]:
import numpy as np

def read_pdb(file_path):
    coordinates = []
    with open(file_path, 'r') as pdb_file:
        for line in pdb_file:
            if line.startswith('ATOM'):
                x = float(line[30:38])
                y = float(line[38:46])
                z = float(line[46:54])
                coordinates.append([x, y, z])
    return np.array(coordinates)

def write_pdb(file_path, coordinates):
    with open(file_path, 'w') as pdb_file:
        with open('tre-copy.pdb', 'r') as original_pdb:
            for line, coord in zip(original_pdb, coordinates):
                x_str = f"{coord[0]:8.3f}"
                y_str = f"{coord[1]:8.3f}"
                z_str = f"{coord[2]:8.3f}"
                new_line = f"{line[:30]}{x_str}{y_str}{z_str}{line[54:]}"
                pdb_file.write(new_line)

file_path = 'tre-copy.pdb'
coordinates = read_pdb(file_path)

print("Matriz de coordenadas cartesianas:")
print(coordinates)

# Definir ángulos de Euler
phi = np.pi / 4  # Ángulo de Euler phi (en radianes)
theta = np.pi / 3  # Ángulo de Euler theta (en radianes)
psi = np.pi / 6  # Ángulo de Euler psi (en radianes)

# Calcular la matriz de rotación
R = euler_rotation_matrix(phi, theta, psi)

# Aplicar la rotación a las coordenadas
rotated_coordinates = np.dot(R, coordinates.T).T

print("\nCoordenadas rotadas:")
print(rotated_coordinates)

# Escribir las coordenadas rotadas en un nuevo archivo PDB
write_pdb('rotated.pdb', rotated_coordinates)


Matriz de coordenadas cartesianas:
[[ 0.613  1.415 -0.392]
 [ 1.163  1.202 -1.711]
 [ 1.057  2.63   0.24 ]
 [-0.927  1.412 -0.444]
 [ 2.59   1.071 -1.719]
 [ 0.559  3.873 -0.298]
 [-1.377  2.591 -1.311]
 [-1.463  0.184 -0.947]
 [ 3.099 -0.009 -0.951]
 [ 3.161  1.088 -3.164]
 [-0.939  3.895 -0.651]
 [ 0.848  4.97   0.745]
 [-2.798  2.61  -1.502]
 [ 2.956 -1.313 -1.531]
 [ 3.262 -0.277 -3.85 ]
 [ 2.432  1.97  -4.045]
 [-1.174  4.983 -1.561]
 [ 0.263  4.618  2.008]
 [ 3.609 -1.438 -2.915]
 [ 3.638 -2.304 -0.556]
 [ 4.289 -0.211 -4.868]
 [ 3.193 -2.684 -3.503]
 [ 4.982 -1.886 -0.285]
 [ 0.932  0.588  0.238]
 [-1.326  1.534  0.568]
 [ 2.971  1.984 -1.252]
 [ 1.144  4.108 -1.196]
 [-0.967  2.514 -2.317]
 [-1.617  0.293 -1.903]
 [ 4.175  1.506 -3.108]
 [-1.561  4.075  0.236]
 [ 1.924  5.072  0.916]
 [ 0.448  5.94   0.447]
 [-3.195  2.002 -0.84 ]
 [ 1.893 -1.569 -1.59 ]
 [ 2.344 -0.496 -4.407]
 [ 1.807  2.48  -3.496]
 [-1.969  4.75  -2.077]
 [ 0.69   3.786  2.281]
 [ 4.695 -1.494 -2.819]
 [ 3.

In [35]:
import numpy as np

def read_pdb(file_path):
    coordinates = []
    with open(file_path, 'r') as pdb_file:
        for line in pdb_file:
            if line.startswith('ATOM'):
                x = float(line[30:38])
                y = float(line[38:46])
                z = float(line[46:54])
                coordinates.append([x, y, z])
    return np.array(coordinates)

def translate(coordinates, distance=4):
    """
    Translada las coordenadas para asegurar que la nueva molécula esté al menos a la distancia especificada
    del anterior.
    
    Args:
        coordinates (numpy.ndarray): Coordenadas cartesianas de la molécula.
        distance (float): Distancia mínima deseada entre las dos moléculas (por defecto 4 Å).
        
    Returns:
        numpy.ndarray: Coordenadas cartesianas trasladadas.
    """
    # Encontrar el centroide de las coordenadas existentes
    centroid = np.mean(coordinates, axis=0)
    
    # Calcular el vector de traslación multiplicando el vector unitario por la distancia deseada
    translation_vector = distance * np.random.rand(3)
    
    # Aplicar la traslación sumando el vector de traslación al centroide
    translated_coordinates = coordinates + translation_vector
    
    return translated_coordinates

def write_pdb(file_path, coordinates, chain_id):
    with open(file_path, 'w') as pdb_file:
        with open('tre-copy.pdb', 'r') as original_pdb:
            for line, coord in zip(original_pdb, coordinates):
                x_str = f"{coord[0]:8.3f}"
                y_str = f"{coord[1]:8.3f}"
                z_str = f"{coord[2]:8.3f}"
                new_line = f"{line[:21]}{chain_id}{line[22:30]}{x_str}{y_str}{z_str}{line[54:]}"
                pdb_file.write(new_line)

file_path = 'tre-copy.pdb'
coordinates = read_pdb(file_path)

print("Matriz de coordenadas cartesianas:")
print(coordinates)

# Definir ángulos de Euler
phi = np.pi / 4  # Ángulo de Euler phi (en radianes)
theta = np.pi / 3  # Ángulo de Euler theta (en radianes)
psi = np.pi / 6  # Ángulo de Euler psi (en radianes)

# Calcular la matriz de rotación
R = euler_rotation_matrix(phi, theta, psi)

# Aplicar la rotación a las coordenadas
rotated_coordinates = np.dot(R, coordinates.T).T

# Trasladar las coordenadas
translated_coordinates = translate(rotated_coordinates)

print("\nCoordenadas trasladadas:")
print(translated_coordinates)

# Escribir las coordenadas rotadas y trasladadas en un nuevo archivo PDB
write_pdb('rotated_translated.pdb', translated_coordinates, 'B')


Matriz de coordenadas cartesianas:
[[ 0.613  1.415 -0.392]
 [ 1.163  1.202 -1.711]
 [ 1.057  2.63   0.24 ]
 [-0.927  1.412 -0.444]
 [ 2.59   1.071 -1.719]
 [ 0.559  3.873 -0.298]
 [-1.377  2.591 -1.311]
 [-1.463  0.184 -0.947]
 [ 3.099 -0.009 -0.951]
 [ 3.161  1.088 -3.164]
 [-0.939  3.895 -0.651]
 [ 0.848  4.97   0.745]
 [-2.798  2.61  -1.502]
 [ 2.956 -1.313 -1.531]
 [ 3.262 -0.277 -3.85 ]
 [ 2.432  1.97  -4.045]
 [-1.174  4.983 -1.561]
 [ 0.263  4.618  2.008]
 [ 3.609 -1.438 -2.915]
 [ 3.638 -2.304 -0.556]
 [ 4.289 -0.211 -4.868]
 [ 3.193 -2.684 -3.503]
 [ 4.982 -1.886 -0.285]
 [ 0.932  0.588  0.238]
 [-1.326  1.534  0.568]
 [ 2.971  1.984 -1.252]
 [ 1.144  4.108 -1.196]
 [-0.967  2.514 -2.317]
 [-1.617  0.293 -1.903]
 [ 4.175  1.506 -3.108]
 [-1.561  4.075  0.236]
 [ 1.924  5.072  0.916]
 [ 0.448  5.94   0.447]
 [-3.195  2.002 -0.84 ]
 [ 1.893 -1.569 -1.59 ]
 [ 2.344 -0.496 -4.407]
 [ 1.807  2.48  -3.496]
 [-1.969  4.75  -2.077]
 [ 0.69   3.786  2.281]
 [ 4.695 -1.494 -2.819]
 [ 3.

In [36]:
def write_combined_pdb(file_path, coordinates1, coordinates2, chain_id1='A', chain_id2='B'):
    with open(file_path, 'w') as pdb_file:
        atom_index = 1
        # Escribir la primera molécula
        for coord in coordinates1:
            x_str = f"{coord[0]:8.3f}"
            y_str = f"{coord[1]:8.3f}"
            z_str = f"{coord[2]:8.3f}"
            line = f"ATOM  {atom_index:5}  CA  GLY {chain_id1}   1    {x_str}{y_str}{z_str}  1.00  0.00      {chain_id1}\n"
            pdb_file.write(line)
            atom_index += 1
        
        # Escribir la segunda molécula
        for coord in coordinates2:
            x_str = f"{coord[0]:8.3f}"
            y_str = f"{coord[1]:8.3f}"
            z_str = f"{coord[2]:8.3f}"
            line = f"ATOM  {atom_index:5}  CA  GLY {chain_id2}   1    {x_str}{y_str}{z_str}  1.00  0.00      {chain_id2}\n"
            pdb_file.write(line)
            atom_index += 1

# Escribir las coordenadas rotadas y trasladadas en un nuevo archivo PDB
write_combined_pdb('combined.pdb', coordinates, translated_coordinates)
