Primer demanem al chat gpt que ens crei una matriu amb les coordenades cartesianes del fitxer pdb en qüestió.

In [2]:
import numpy as np

def read_pdb(file_path):
    coordinates = []
    with open(file_path, 'r') as pdb_file:
        for line in pdb_file:
            if line.startswith('ATOM'):
                x = float(line[30:38])
                y = float(line[38:46])
                z = float(line[46:54])
                coordinates.append([x, y, z])
    return np.array(coordinates)

# Ruta al archivo PDB
file_path = 'tre-copy.pdb'

# Leer el archivo PDB y crear la matriz de coordenadas
coordinates = read_pdb(file_path)

print("Matriz de coordenadas cartesianas:")
print(coordinates)


Matriz de coordenadas cartesianas:
[[ 0.613  1.415 -0.392]
 [ 1.163  1.202 -1.711]
 [ 1.057  2.63   0.24 ]
 [-0.927  1.412 -0.444]
 [ 2.59   1.071 -1.719]
 [ 0.559  3.873 -0.298]
 [-1.377  2.591 -1.311]
 [-1.463  0.184 -0.947]
 [ 3.099 -0.009 -0.951]
 [ 3.161  1.088 -3.164]
 [-0.939  3.895 -0.651]
 [ 0.848  4.97   0.745]
 [-2.798  2.61  -1.502]
 [ 2.956 -1.313 -1.531]
 [ 3.262 -0.277 -3.85 ]
 [ 2.432  1.97  -4.045]
 [-1.174  4.983 -1.561]
 [ 0.263  4.618  2.008]
 [ 3.609 -1.438 -2.915]
 [ 3.638 -2.304 -0.556]
 [ 4.289 -0.211 -4.868]
 [ 3.193 -2.684 -3.503]
 [ 4.982 -1.886 -0.285]
 [ 0.932  0.588  0.238]
 [-1.326  1.534  0.568]
 [ 2.971  1.984 -1.252]
 [ 1.144  4.108 -1.196]
 [-0.967  2.514 -2.317]
 [-1.617  0.293 -1.903]
 [ 4.175  1.506 -3.108]
 [-1.561  4.075  0.236]
 [ 1.924  5.072  0.916]
 [ 0.448  5.94   0.447]
 [-3.195  2.002 -0.84 ]
 [ 1.893 -1.569 -1.59 ]
 [ 2.344 -0.496 -4.407]
 [ 1.807  2.48  -3.496]
 [-1.969  4.75  -2.077]
 [ 0.69   3.786  2.281]
 [ 4.695 -1.494 -2.819]
 [ 3.

Un cop tenim les coordenades cartesianes de la molècula, demanem al chat gpt que ens faci la transposada de la matriu resultant.

In [3]:
transposed_coordinates = coordinates.transpose()  # Método transpose()
# O también puedes usar: transposed_coordinates = coordinates.T  # Propiedad .T

print("\nMatriz transpuesta de coordenadas cartesianas:")
print(transposed_coordinates)


Matriz transpuesta de coordenadas cartesianas:
[[ 0.613  1.163  1.057 -0.927  2.59   0.559 -1.377 -1.463  3.099  3.161
  -0.939  0.848 -2.798  2.956  3.262  2.432 -1.174  0.263  3.609  3.638
   4.289  3.193  4.982  0.932 -1.326  2.971  1.144 -0.967 -1.617  4.175
  -1.561  1.924  0.448 -3.195  1.893  2.344  1.807 -1.969  0.69   4.695
   3.113  3.671  4.075  2.336  4.927]
 [ 1.415  1.202  2.63   1.412  1.071  3.873  2.591  0.184 -0.009  1.088
   3.895  4.97   2.61  -1.313 -0.277  1.97   4.983  4.618 -1.438 -2.304
  -0.211 -2.684 -1.886  0.588  1.534  1.984  4.108  2.514  0.293  1.506
   4.075  5.072  5.94   2.002 -1.569 -0.496  2.48   4.75   3.786 -1.494
  -2.318 -3.318  0.544 -2.568 -0.943]
 [-0.392 -1.711  0.24  -0.444 -1.719 -0.298 -1.311 -0.947 -0.951 -3.164
  -0.651  0.745 -1.502 -1.531 -3.85  -4.045 -1.561  2.008 -2.915 -0.556
  -4.868 -3.503 -0.285  0.238  0.568 -1.252 -1.196 -2.317 -1.903 -3.108
   0.236  0.916  0.447 -0.84  -1.59  -4.407 -3.496 -2.077  2.281 -2.819
   0.397 -0.

Ara demanem que ens crei un matriu de rotació 3d segons els angles de euller

In [4]:
import numpy as np

def euler_rotation_matrix(phi, theta, psi):
    """
    Calcula la matriz de rotación en 3D según los ángulos de Euler (phi, theta, psi).
    
    Args:
        phi (float): Ángulo de Euler phi en radianes.
        theta (float): Ángulo de Euler theta en radianes.
        psi (float): Ángulo de Euler psi en radianes.
        
    Returns:
        numpy.ndarray: Matriz de rotación en 3D.
    """
    R_x = np.array([[1, 0, 0],
                    [0, np.cos(phi), -np.sin(phi)],
                    [0, np.sin(phi), np.cos(phi)]])
    
    R_y = np.array([[np.cos(theta), 0, np.sin(theta)],
                    [0, 1, 0],
                    [-np.sin(theta), 0, np.cos(theta)]])
    
    R_z = np.array([[np.cos(psi), -np.sin(psi), 0],
                    [np.sin(psi), np.cos(psi), 0],
                    [0, 0, 1]])
    
    # Combinar las tres rotaciones
    R = np.dot(R_z, np.dot(R_y, R_x))
    
    return R

# Ejemplo de uso
phi = np.pi/4  # Ángulo de Euler phi (en radianes)
theta = np.pi/3  # Ángulo de Euler theta (en radianes)
psi = np.pi/6  # Ángulo de Euler psi (en radianes)

# Calcular la matriz de rotación
R = euler_rotation_matrix(phi, theta, psi)

print("Matriz de rotación:")
print(R)


Matriz de rotación:
[[ 0.4330127   0.1767767   0.88388348]
 [ 0.25        0.91855865 -0.30618622]
 [-0.8660254   0.35355339  0.35355339]]


Multipliquem la matriu de rotació per la matriu transposada

In [5]:
R@transposed_coordinates

array([[ 1.69093487e-01, -7.96245268e-01,  1.13474917e+00,
        -5.44238344e-01, -2.08564958e-01,  6.63312965e-01,
        -1.29700131e+00, -1.43800832e+00,  4.99742187e-01,
        -1.23552112e+00, -2.93461842e-01,  1.90426814e+00,
        -2.07777535e+00, -3.05347857e-01, -2.03943110e+00,
        -2.17397168e+00, -1.00722075e+00,  2.70507514e+00,
        -1.26798238e+00,  6.76567491e-01, -2.48285317e+00,
        -2.18810291e+00,  1.57196164e+00,  7.17876802e-01,
         1.99046423e-01,  5.30583588e-01,  1.64440557e-01,
        -2.02226469e+00, -2.33041622e+00, -6.73056111e-01,
         2.53028706e-01,  2.53936510e+00,  1.63913917e+00,
        -1.77203076e+00, -8.63044318e-01, -2.96797395e+00,
        -1.86919648e+00, -1.84873869e+00,  2.98419354e+00,
        -7.22777268e-01,  1.28910190e+00,  1.53632533e-01,
        -2.95116836e+00, -2.92936520e+00,  1.92963005e+00],
       [ 1.57303549e+00,  1.91874212e+00,  2.60657457e+00,
         1.20120150e+00,  2.15761043e+00,  3.78857116e+

Demanem el programa complert

In [11]:
import numpy as np

def read_pdb(file_path):
    coordinates = []
    with open(file_path, 'r') as pdb_file:
        for line in pdb_file:
            if line.startswith('ATOM'):
                x = float(line[30:38])
                y = float(line[38:46])
                z = float(line[46:54])
                coordinates.append([x, y, z])
    return np.array(coordinates)

def write_pdb(file_path, coordinates):
    with open(file_path, 'w') as pdb_file:
        with open('tre-copy.pdb', 'r') as template:
            for line, coord in zip(template, coordinates):
                x_str = f"{coord[0]:8.3f}"
                y_str = f"{coord[1]:8.3f}"
                z_str = f"{coord[2]:8.3f}"
                new_line = f"{line[:30]}{x_str}{y_str}{z_str}{line[54:]}"
                pdb_file.write(new_line)

def euler_rotation_matrix(phi, theta, psi):
    R_x = np.array([[1, 0, 0],
                    [0, np.cos(phi), -np.sin(phi)],
                    [0, np.sin(phi), np.cos(phi)]])
    
    R_y = np.array([[np.cos(theta), 0, np.sin(theta)],
                    [0, 1, 0],
                    [-np.sin(theta), 0, np.cos(theta)]])
    
    R_z = np.array([[np.cos(psi), -np.sin(psi), 0],
                    [np.sin(psi), np.cos(psi), 0],
                    [0, 0, 1]])
    
    R = np.dot(R_z, np.dot(R_y, R_x))
    
    return R

def apply_rotation(phi, theta, psi):
    file_path = 'tre-copy.pdb'
    
    # Leer el archivo PDB y crear la matriz de coordenadas
    coordinates = read_pdb(file_path)
    
    # Calcular la matriz de rotación
    R = euler_rotation_matrix(phi, theta, psi)
    
    # Calcular la transpuesta de la matriz de coordenadas
    transposed_coordinates = coordinates.T
    
    # Aplicar la rotación multiplicando la matriz de rotación por la transpuesta de las coordenadas
    rotated_coordinates = np.dot(R, transposed_coordinates)
    
    # Transponer el resultado para obtener las coordenadas finales
    final_coordinates = rotated_coordinates.T
    
    # Escribir las coordenadas rotadas en un nuevo archivo PDB
    write_pdb('rotated2.pdb', final_coordinates)

# Ángulos de Euler
phi = np.pi / 4  # Ángulo de Euler phi (en radianes)
theta = np.pi / 3  # Ángulo de Euler theta (en radianes)
psi = np.pi / 6  # Ángulo de Euler psi (en radianes)

# Aplicar la rotación para el archivo "tre-copy.pdb"
apply_rotation(phi, theta, psi)


Arxius iguals

In [13]:
import numpy as np
import os

def read_pdb(file_path):
    coordinates = []
    with open(file_path, 'r') as pdb_file:
        for line in pdb_file:
            if line.startswith('ATOM'):
                x = float(line[30:38])
                y = float(line[38:46])
                z = float(line[46:54])
                coordinates.append([x, y, z])
    return np.array(coordinates)

def write_pdb(file_path, coordinates):
    with open(file_path, 'w') as pdb_file:
        with open('tre-copy.pdb', 'r') as template:
            for line, coord in zip(template, coordinates):
                x_str = f"{coord[0]:8.3f}"
                y_str = f"{coord[1]:8.3f}"
                z_str = f"{coord[2]:8.3f}"
                new_line = f"{line[:30]}{x_str}{y_str}{z_str}{line[54:]}"
                pdb_file.write(new_line)

def euler_rotation_matrix(phi, theta, psi):
    R_x = np.array([[1, 0, 0],
                    [0, np.cos(phi), -np.sin(phi)],
                    [0, np.sin(phi), np.cos(phi)]])
    
    R_y = np.array([[np.cos(theta), 0, np.sin(theta)],
                    [0, 1, 0],
                    [-np.sin(theta), 0, np.cos(theta)]])
    
    R_z = np.array([[np.cos(psi), -np.sin(psi), 0],
                    [np.sin(psi), np.cos(psi), 0],
                    [0, 0, 1]])
    
    R = np.dot(R_z, np.dot(R_y, R_x))
    
    return R

def apply_rotation(file_path, phi, theta, psi):
    # Leer el archivo PDB y crear la matriz de coordenadas
    coordinates = read_pdb(file_path)
    
    # Calcular la matriz de rotación
    R = euler_rotation_matrix(phi, theta, psi)
    
    # Calcular la transpuesta de la matriz de coordenadas
    transposed_coordinates = coordinates.T
    
    # Aplicar la rotación multiplicando la matriz de rotación por la transpuesta de las coordenadas
    rotated_coordinates = np.dot(R, transposed_coordinates)
    
    # Transponer el resultado para obtener las coordenadas finales
    final_coordinates = rotated_coordinates.T
    
    return final_coordinates

# Ángulos de Euler
phi = np.pi / 4  # Ángulo de Euler phi (en radianes)
theta = np.pi / 3  # Ángulo de Euler theta (en radianes)
psi = np.pi / 6  # Ángulo de Euler psi (en radianes)

# Crear 10 archivos PDB nuevos con coordenadas rotadas
output_directory = "output"
os.makedirs(output_directory, exist_ok=True)

for i in range(10):
    rotated_coordinates = apply_rotation('tre-copy.pdb', phi, theta, psi)
    output_file_path = os.path.join(output_directory, f'rotated_{i+1}.pdb')
    write_pdb(output_file_path, rotated_coordinates)
    print(f"Archivo {output_file_path} creado con éxito.")


Archivo output/rotated_1.pdb creado con éxito.
Archivo output/rotated_2.pdb creado con éxito.
Archivo output/rotated_3.pdb creado con éxito.
Archivo output/rotated_4.pdb creado con éxito.
Archivo output/rotated_5.pdb creado con éxito.
Archivo output/rotated_6.pdb creado con éxito.
Archivo output/rotated_7.pdb creado con éxito.
Archivo output/rotated_8.pdb creado con éxito.
Archivo output/rotated_9.pdb creado con éxito.
Archivo output/rotated_10.pdb creado con éxito.


provem un nou que li demanem

In [14]:
import numpy as np
import os

def read_pdb(file_path):
    coordinates = []
    with open(file_path, 'r') as pdb_file:
        for line in pdb_file:
            if line.startswith('ATOM'):
                x = float(line[30:38])
                y = float(line[38:46])
                z = float(line[46:54])
                coordinates.append([x, y, z])
    return np.array(coordinates)

def write_pdb(file_path, coordinates):
    with open(file_path, 'w') as pdb_file:
        with open('tre-copy.pdb', 'r') as template:
            for line, coord in zip(template, coordinates):
                x_str = f"{coord[0]:8.3f}"
                y_str = f"{coord[1]:8.3f}"
                z_str = f"{coord[2]:8.3f}"
                new_line = f"{line[:30]}{x_str}{y_str}{z_str}{line[54:]}"
                pdb_file.write(new_line)

def euler_rotation_matrix(phi, theta, psi):
    R_x = np.array([[1, 0, 0],
                    [0, np.cos(phi), -np.sin(phi)],
                    [0, np.sin(phi), np.cos(phi)]])
    
    R_y = np.array([[np.cos(theta), 0, np.sin(theta)],
                    [0, 1, 0],
                    [-np.sin(theta), 0, np.cos(theta)]])
    
    R_z = np.array([[np.cos(psi), -np.sin(psi), 0],
                    [np.sin(psi), np.cos(psi), 0],
                    [0, 0, 1]])
    
    R = np.dot(R_z, np.dot(R_y, R_x))
    
    return R

def apply_rotation(file_path, phi, theta, psi):
    # Leer el archivo PDB y crear la matriz de coordenadas
    coordinates = read_pdb(file_path)
    
    # Calcular la matriz de rotación
    R = euler_rotation_matrix(phi, theta, psi)
    
    # Calcular la transpuesta de la matriz de coordenadas
    transposed_coordinates = coordinates.T
    
    # Aplicar la rotación multiplicando la matriz de rotación por la transpuesta de las coordenadas
    rotated_coordinates = np.dot(R, transposed_coordinates)
    
    # Transponer el resultado para obtener las coordenadas finales
    final_coordinates = rotated_coordinates.T
    
    return final_coordinates

# Ángulos de Euler originales
phi = np.pi / 4  # Ángulo de Euler phi (en radianes)
theta = np.pi / 3  # Ángulo de Euler theta (en radianes)
psi = np.pi / 6  # Ángulo de Euler psi (en radianes)

# Crear 10 archivos PDB nuevos con coordenadas rotadas
output_directory = "output_random"
os.makedirs(output_directory, exist_ok=True)

for i in range(10):
    # Introducir variaciones aleatorias en los ángulos de Euler
    phi_random = phi + np.random.uniform(-np.pi/12, np.pi/12)  # Variación de +/- 15 grados
    theta_random = theta + np.random.uniform(-np.pi/12, np.pi/12)
    psi_random = psi + np.random.uniform(-np.pi/12, np.pi/12)
    
    rotated_coordinates = apply_rotation('tre-copy.pdb', phi_random, theta_random, psi_random)
    output_file_path = os.path.join(output_directory, f'rotated_{i+1}.pdb')
    write_pdb(output_file_path, rotated_coordinates)
    print(f"Archivo {output_file_path} creado con éxito.")


Archivo output_random/rotated_1.pdb creado con éxito.
Archivo output_random/rotated_2.pdb creado con éxito.
Archivo output_random/rotated_3.pdb creado con éxito.
Archivo output_random/rotated_4.pdb creado con éxito.
Archivo output_random/rotated_5.pdb creado con éxito.
Archivo output_random/rotated_6.pdb creado con éxito.
Archivo output_random/rotated_7.pdb creado con éxito.
Archivo output_random/rotated_8.pdb creado con éxito.
Archivo output_random/rotated_9.pdb creado con éxito.
Archivo output_random/rotated_10.pdb creado con éxito.


Demanem que ens fusioni els pdb en un únic, i que les separi uns 3 angstroms

In [15]:
import os

def merge_pdbs(input_directory, output_file, separation_distance=3.0):
    with open(output_file, 'w') as out_pdb:
        atom_counter = 1
        for file_name in os.listdir(input_directory):
            if file_name.endswith('.pdb'):
                pdb_file = os.path.join(input_directory, file_name)
                with open(pdb_file, 'r') as in_pdb:
                    for line in in_pdb:
                        if line.startswith('ATOM'):
                            out_pdb.write(f"{line[:30]}{atom_counter:4}{line[34:]}")
                            atom_counter += 1
                # Añadir un espacio entre las moléculas
                out_pdb.write(f"TER\n")
                atom_counter = 1
                # Añadir separación entre las moléculas
                out_pdb.write(f"TER    {separation_distance:8.3f}   {separation_distance:8.3f}   {separation_distance:8.3f}\n")

# Directorio donde se encuentran los archivos PDB a fusionar
input_directory = "output_random"
# Nombre del archivo PDB de salida
output_file = "merged.pdb"

# Fusionar los archivos PDB en uno solo con separación de 3 Å entre moléculas
merge_pdbs(input_directory, output_file, separation_distance=3.0)

print(f"Archivos PDB fusionados en '{output_file}' con éxito.")


Archivos PDB fusionados en 'merged.pdb' con éxito.


el fitxer fusionat es veu molt malament, allarguem la distància

In [16]:
import os

def merge_pdbs(input_directory, output_file, separation_distance=10.0):
    with open(output_file, 'w') as out_pdb:
        atom_counter = 1
        for file_name in os.listdir(input_directory):
            if file_name.endswith('.pdb'):
                pdb_file = os.path.join(input_directory, file_name)
                with open(pdb_file, 'r') as in_pdb:
                    for line in in_pdb:
                        if line.startswith('ATOM'):
                            out_pdb.write(f"{line[:30]}{atom_counter:4}{line[34:]}")
                            atom_counter += 1
                # Añadir un espacio entre las moléculas
                out_pdb.write(f"TER\n")
                atom_counter = 1
                # Añadir separación entre las moléculas
                out_pdb.write(f"TER    {separation_distance:8.3f}   {separation_distance:8.3f}   {separation_distance:8.3f}\n")

# Directorio donde se encuentran los archivos PDB a fusionar
input_directory = "output_random"
# Nombre del archivo PDB de salida
output_file = "merged_10A.pdb"

# Fusionar los archivos PDB en uno solo con separación de 10 Å entre moléculas
merge_pdbs(input_directory, output_file, separation_distance=10.0)

print(f"Archivos PDB fusionados en '{output_file}' con éxito.")


Archivos PDB fusionados en 'merged_10A.pdb' con éxito.
